config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #get 'welcome/index'
  #resources:blogs
  resources :blogs do
	  resources :comments
	end
  root 'blogs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	 has_many :comments, dependent: :destroy
	 mount_uploader :image, AvatarUploader
	 # attr_accessor :option
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!
  def index
    if params[:search].present?
      @blogs= Blog.where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
    elsif params[:start_date].present? && params[:end_date].present?
        @blogs = Blog.where('created_at >= ? AND created_at <= ?', params[:start_date].to_date, params[:end_date].to_date)  
    else
       @blogs=Blog.all
    end

    end
  def new
    @blog=Blog.new
	end

	def create
     @blog = Blog.new(blog_params)
 
     @blog.save
     redirect_to @blog
   end

  def show
    @blog = Blog.find(params[:id])
  end


      def edit
  @blog=Blog.find(params[:id])

   end

  def update
    @blog=Blog.find(params[:id])
    @blog.update(blog_params)
   end
	def destroy
    @blog=Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end
  

   
	private
  def blog_params
    params.require(:blog).permit(:title, :description, :image, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

  private

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to blog_path(@blog)
  end

  def edit
     @blog = Blog.find(params[:blog_id])
     @comment = Comment.find(params[:id])
  end

 def destroy
    #@article = Article.find(params[:id])
    #@comment = @article.comments.find(params[:article_id])
    @blog = Blog.find(params[:blog_id])
     @comment = Comment.find(params[:id])
    @comment.destroy
    #redirect_to article_path(@article)
    redirect_to blog_path(@blog)

  end

  def update
     @blog = Blog.find(params[:blog_id])
     @comment = Comment.find(params[:id])
     if @comment.update(comment_params)
      flash[:notice] = "Comment Updated"

   redirect_to blog_path(@blog)
     else
      render 'edit'
   end
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroyconfig.app_generators.scaffold_controller = :scaffold_controller

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/edit.html.erb
<%= form_for :blog, url: blog_path(@blog), method: :patch do |f| %>
<p>
<%=f.label :title%>
<%=f.text_field :title%>
</p>

<p>
<%=f.label :description%>
<%=f.text_field :description%>
</p>
<p>
  <strong>Category:</strong>
  <%= f.select(:category_id, Category.all.collect {|u| [u.name, u.id]}, :prompt => 'Select Category') %>
</p>
<p>
<%=f.label :image%>
<%=f.file_field :image%>
</p>
<p>
<%=f.submit %>
</p>
<%end%>
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<% if params[:search].present? %>
<h3> <%= @blogs.count%> Results found.</h3>
<%end %>
<h1>blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>image</th>
      <th>Category</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
         <td><%= blog.description %></td>
       
        <td><%= image_tag blog.image, :height=>"300", :width=>"300" %></td>
        <td>
        <%if blog.category_id.present? %>
            <%=Category.find(blog.category_id).name %>
        <% end %>
          
        </td>
        <td><%= link_to 'Show', blog %></td>
       
          <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
          <td><%= link_to 'Destroy', blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
   
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>
</div>

app/views/blogs/new.html.erb
  <%=form_for :blog, url:blogs_path do |f|%>
<p>
<%=f.label :title%>
<%=f.text_field :title%>
</p>
<p>
<%=f.label :description%>
<%=f.text_field :description%>
</p>

<p>
<%=f.label :image%>
<%=f.file_field :image%>
</p></br>
<p>
<%#= f.select :category_id, [['All', 1], ['Co', 2], ['Bought', 3], ['View', 4], ['Top API', 5]]  %>
<%= f.select(:category_id, Category.all.collect {|u| [u.created_at, u.id]}, :prompt => 'Select Category') %>
</p>
<p>
<%=f.submit %>
</p>
<%end%>
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
 <%if @blog.category_id.present? %>
<p>
  <strong>Category:</strong>
  <%=Category.find(@blog.category_id).name %>
</p>
<%end%>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

    <p>
   <strong>description:</strong>
  <%= @blog.description %>
   </p>

   <p>
  <strong>image:</strong>
  <%= image_tag @blog.image, :height=>"100", :width=>"100" %>

<% @blog.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body%> 
     </p>
     
<%= link_to 'Edit Comment',edit_blog_comment_path(@blog, comment)%>
      <%#= link_to 'Destroy Comment',article_comment_path(@article,comment),method: :delete, data: { confirm: 'Are you sure,you want to delete' } %>

      <%= link_to 'Destroy Comment',"/blogs/#{@blog.id}/comments/#{comment.id}",method: :delete, data: { confirm: 'Are you sure,you want to delete' } %>
      

<%end%>
   
       <h2>Add a comment:</h2>
<%= form_for([@blog, @blog.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
    <%= link_to 'Back', blogs_path %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],method: :delete, data: { confirm: 'Are you sure do have comment' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@blog, @blog.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>


<%#= form_for([@article, @comment]) do |f| %>
<%= form_for(:comment, url: "/blogs/#{@blog.id}/comments") do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <!--

  <div class="container">
    <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form> --> .
 <div class="container">

  <div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <%=form_tag "/blogs" ,:method=>"GET" do %>

      <%= text_field_tag :search, params[:search] , :placeholder => "Type here to search"%>
      <%= text_field_tag :start_date, params[:start_date] , :placeholder => "Start date", :id=>"start-date"%>
      <%= text_field_tag :end_date, params[:end_date] , :placeholder => "end_date" , :id=>"end-date"%>
      <%= submit_tag "Search", :class=>"btn btn-success"%>
    <%end%>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div><br>
 
  </div>

    <%= yield %>
  </body>
</html>
<script>
  $( function() {
    $("#start-date" ).datepicker({ dateFormat: 'dd-mm-yy' });
    $("#end-date" ).datepicker({ dateFormat: 'dd-mm-yy' });
  } );
  </script>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>hello rails</h1>